hibernate.dialect = org.hibernate.dialect.MySQLDialect
hibernate.connection.driver_class = com.mysql.jdbc.Driver
hibernate.connection.url = jdbc:mysql://localhost:3306/exo_db
hibernate.connection.username = root
hibernate.connection.password = root
hibernate.show-sql = true
hibernate.hbm2ddl.auto=create
hibernate.connection.autocommit = false